#!/bin/bash 

CMD="dotnet test"
 
echo "EXECUTE $CMD"
# Check if we actually have commits to push

commits=`git log @{u}..`

if [ -z "$commits" ]; then
    exit 0
fi

current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

$CMD
RESULT=$?
if [ $RESULT -ne 0 ]; then 
       echo "failed $CMD"
       exit 1
fi
exit 0

