#!/bin/bash 

CMD="dotnet build"
 
echo "EXECUTE $CMD"

current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

$CMD
RESULT=$?
if [ $RESULT -ne 0 ]; then 
       echo "failed $CMD"
       exit 1
fi


echo "EXECUTE FORMATTER"
LC_ALL=C

# Select files to format
FILES=$(git diff --cached --name-only --diff-filter=ACM "*.cs" | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Format all selected files
echo "$FILES" | cat | xargs | sed -e 's/ /,/g' | xargs dotnet-format --include

# Add back the modified files to staging
echo "$FILES" | xargs git add

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ]; then
  echo "Commit impossible sur la branche master"
  exit 1
fi


exit 0
